-- install_map_world (-- world-map v3 (Oct 1 2026)): ONE draggable world map in the LIVE workspace.HudBarUI.HudBarClient.
-- Generated by boundary/patch_map_world.py from boundary/hudbar_map_block.lua - edit those, not this. Edit mode; re-runnable.
local s = workspace:WaitForChild("HudBarUI"):WaitForChild("HudBarClient")
local MARK = [==[-- world-map v3 (Oct 1 2026)]==]
local END = [==[-- Passport entry uses the same top-right control row]==]
local BLOCK = [==[local MAP_ID = 126434655912945
-- ONE draggable chart of the whole world (Shannon's choice, Oct 1 2026): France, the gorge the river leaves through, the
-- falls, Porto Nocciola's harbour and shore, drawn as one parchment (marketing/make_map_world.py). The panel is a window
-- onto it: drag with the mouse or a finger, zoom with the wheel, a pinch or the + / - buttons, "Me" centres on you. The
-- names, tallies, the "?" covers over places you have not reached and the you-are-here dot ride on the chart.
local IMG_W, IMG_H, IMG_M = 1024, 900, 26                     -- the image, and the margin its world area starts at
local WX0, WX1, WZ0, WZ1 = -130, 700, -700, 30                -- the world the image covers (make_map_world.py)
local IS = math.min((IMG_W - 2 * IMG_M) / (WX1 - WX0), (IMG_H - 2 * IMG_M) / (WZ1 - WZ0))
local IOX = (IMG_W - (WX1 - WX0) * IS) / 2
local IOZ = (IMG_H - (WZ1 - WZ0) * IS) / 2
local function toImg(x, z) return IOX + (x - WX0) * IS, IOZ + (z - WZ0) * IS end   -- world -> chart pixels
local DISP_W, DISP_H = 560, 380                                   -- the window onto the chart
local MINZ, MAXZ = math.min(DISP_W / IMG_W, DISP_H / IMG_H), 2.6   -- the whole world .. close up
local zoom, panX, panY = 1, 0, 0                                  -- chart pixels -> window pixels, and where the chart's corner sits

local map = Instance.new("Frame"); map.Name = "MapPanel"; map.AnchorPoint = Vector2.new(1, 0); map.Position = UDim2.new(1, -10, 0, PANEL_Y)
map.Size = UDim2.fromOffset(DISP_W + 16, DISP_H + 48); map.BackgroundColor3 = PANEL; map.BackgroundTransparency = 0.08
map.BorderSizePixel = 0; map.Visible = false; map.Parent = gui
local mc = Instance.new("UICorner"); mc.CornerRadius = UDim.new(0, 14); mc.Parent = map
local ms = Instance.new("UIStroke"); ms.Color = GOLD; ms.Thickness = 2; ms.Parent = map
local here = Instance.new("TextLabel"); here.Size = UDim2.new(1, -20, 0, 26); here.Position = UDim2.new(0, 10, 0, 6); here.BackgroundTransparency = 1
here.Font = Enum.Font.FredokaOne; here.TextSize = 17; here.TextColor3 = CREAM; here.TextXAlignment = Enum.TextXAlignment.Left
here.TextTruncate = Enum.TextTruncate.AtEnd; here.Text = "You are here"; here.Parent = map
local view = Instance.new("Frame"); view.Name = "View"; view.Position = UDim2.new(0, 8, 0, 36); view.Size = UDim2.fromOffset(DISP_W, DISP_H)
view.BackgroundColor3 = C(214, 190, 140); view.BorderSizePixel = 0; view.ClipsDescendants = true; view.Active = true; view.Parent = map
local vc = Instance.new("UICorner"); vc.CornerRadius = UDim.new(0, 8); vc.Parent = view
local chart = Instance.new("ImageLabel"); chart.Name = "Chart"; chart.BackgroundTransparency = 1; chart.Image = "rbxassetid://" .. MAP_ID
chart.ScaleType = Enum.ScaleType.Stretch; chart.Parent = view
-- the zoom and centre buttons sit in the window's bottom corner (the top of the panel is where the game's notices appear)
local function viewBtn(text, bottom, w)
	local b = Instance.new("TextButton"); b.Name = "Btn_" .. text; b.AnchorPoint = Vector2.new(1, 1); b.Position = UDim2.new(1, -8, 1, -bottom); b.Size = UDim2.fromOffset(w, 30)
	b.BackgroundColor3 = C(58, 48, 76); b.BackgroundTransparency = 0.08; b.BorderSizePixel = 0; b.Font = Enum.Font.FredokaOne; b.TextSize = 18; b.TextColor3 = CREAM
	b.Text = text; b.AutoButtonColor = true; b.ZIndex = 8; b.Parent = view
	local bc = Instance.new("UICorner"); bc.CornerRadius = UDim.new(0, 9); bc.Parent = b
	local bs = Instance.new("UIStroke"); bs.Color = GOLD; bs.Thickness = 1; bs.Transparency = 0.4; bs.Parent = b
	return b
end
local centreMe, zoomOut, zoomIn = viewBtn("Me", 8, 46), viewBtn("-", 46, 30), viewBtn("+", 84, 30)

local layouts = {}                                                -- everything that rides on the chart re-places itself here
local function clampPan()
	local cw, ch = IMG_W * zoom, IMG_H * zoom
	panX = cw <= DISP_W and (DISP_W - cw) / 2 or math.clamp(panX, DISP_W - cw, 0)
	panY = ch <= DISP_H and (DISP_H - ch) / 2 or math.clamp(panY, DISP_H - ch, 0)
end
local function relayout()
	clampPan()
	chart.Position = UDim2.fromOffset(panX, panY); chart.Size = UDim2.fromOffset(IMG_W * zoom, IMG_H * zoom)
	for _, f in ipairs(layouts) do f() end
end
local function toCanvas(x, z) local ix, iz = toImg(x, z) return ix * zoom, iz * zoom end   -- world -> pixels on the chart frame
local function centreOn(x, z) local ix, iz = toImg(x, z); panX = DISP_W / 2 - ix * zoom; panY = DISP_H / 2 - iz * zoom; relayout() end
local function zoomAt(f, vx, vy)                                  -- zoom about a point of the window
	local nz = math.clamp(zoom * f, MINZ, MAXZ); if nz == zoom then return end
	local ix, iy = (vx - panX) / zoom, (vy - panY) / zoom
	zoom = nz; panX = vx - ix * zoom; panY = vy - iy * zoom; relayout()
end
local function viewPoint(sx, sy)                                  -- a screen position -> window pixels (the panel is scaled down on phones)
	local s = math.max(view.AbsoluteSize.X / DISP_W, 0.01)
	return (sx - view.AbsolutePosition.X) / s, (sy - view.AbsolutePosition.Y) / s
end

local cards = {}
for _, a in ipairs(AREAS) do
	local card = {open = false}
	local holder = Instance.new("Frame"); holder.Name = a.id; holder.BackgroundTransparency = 1; holder.Parent = chart
	-- the cover that hides an area you have not reached
	local cover = Instance.new("Frame"); cover.Name = "Cover"; cover.Size = UDim2.fromScale(1, 1); cover.BackgroundColor3 = C(226, 208, 166)
	cover.BorderSizePixel = 0; cover.Parent = holder
	local cs = Instance.new("UIStroke"); cs.Color = C(150, 118, 74); cs.Thickness = 2; cs.Parent = cover
	local q = Instance.new("TextLabel"); q.Size = UDim2.fromScale(1, 1); q.BackgroundTransparency = 1; q.Font = Enum.Font.Antique
	q.TextSize = 44; q.TextColor3 = C(126, 96, 58); q.Text = "?"; q.Parent = cover
	-- the name plate for an area you have reached
	local plate = Instance.new("Frame"); plate.Name = "Plate"; plate.AnchorPoint = Vector2.new(0.5, 0); plate.Position = UDim2.new(0.5, 0, 0, 4)
	plate.Size = UDim2.fromOffset(190, 34); plate.BackgroundColor3 = C(248, 240, 214); plate.BackgroundTransparency = 0.12
	plate.BorderSizePixel = 0; plate.Parent = holder
	local pc = Instance.new("UICorner"); pc.CornerRadius = UDim.new(0, 6); pc.Parent = plate
	local pstroke = Instance.new("UIStroke"); pstroke.Color = C(150, 118, 74); pstroke.Thickness = 1; pstroke.Parent = plate
	local title = Instance.new("TextLabel"); title.Name = "Title"; title.Size = UDim2.new(1, -6, 0, 17); title.Position = UDim2.new(0, 3, 0, 2)
	title.BackgroundTransparency = 1; title.Font = Enum.Font.Antique; title.TextSize = 15; title.TextColor3 = C(88, 58, 32)
	title.TextTruncate = Enum.TextTruncate.AtEnd; title.Parent = plate
	local tally = Instance.new("TextLabel"); tally.Name = "Tally"; tally.Size = UDim2.new(1, -6, 0, 13); tally.Position = UDim2.new(0, 3, 0, 18)
	tally.BackgroundTransparency = 1; tally.Font = Enum.Font.FredokaOne; tally.TextSize = 12; tally.TextColor3 = C(120, 84, 44); tally.Parent = plate
	card.cover, card.plate, card.title, card.tally = cover, plate, title, tally
	table.insert(layouts, function()
		local x0, z0 = toCanvas(a.x0, a.z0); local x1, z1 = toCanvas(a.x1, a.z1)
		holder.Position = UDim2.fromOffset(x0, z0); holder.Size = UDim2.fromOffset(x1 - x0, z1 - z0)
		plate.Size = UDim2.fromOffset(math.max(70, math.min(x1 - x0 - 8, 190)), 34)
		plate.Visible = card.open and (x1 - x0) > 80                -- too small to read: the chart speaks for itself
		cover.Visible = not card.open
		q.TextSize = math.clamp(44 * zoom, 16, 72)
	end)
	cards[a.id] = card
end

local dot = Instance.new("Frame"); dot.Name = "You"; dot.Size = UDim2.fromOffset(13, 13); dot.AnchorPoint = Vector2.new(0.5, 0.5)
dot.BackgroundColor3 = C(210, 50, 50); dot.BorderSizePixel = 0; dot.ZIndex = 6; dot.Parent = chart
local dc = Instance.new("UICorner"); dc.CornerRadius = UDim.new(1, 0); dc.Parent = dot
local ds = Instance.new("UIStroke"); ds.Color = C(252, 246, 230); ds.Thickness = 2; ds.Parent = dot
local ring = Instance.new("Frame"); ring.Size = UDim2.fromOffset(26, 26); ring.AnchorPoint = Vector2.new(0.5, 0.5); ring.Position = UDim2.fromScale(0.5, 0.5)
ring.BackgroundTransparency = 1; ring.ZIndex = 5; ring.Parent = dot
local rc = Instance.new("UICorner"); rc.CornerRadius = UDim.new(1, 0); rc.Parent = ring
local rs = Instance.new("UIStroke"); rs.Color = C(210, 70, 70); rs.Thickness = 2; rs.Transparency = 0.4; rs.Parent = ring

-- dragging and zooming: the mouse or a finger drags, the wheel or a pinch zooms, the buttons too
local drag, pinch = nil, nil
local touches = {}
local function touchCount() local n = 0 for _ in pairs(touches) do n += 1 end return n end
local function pinchUpdate()
	local pts = {}
	for _, v in pairs(touches) do pts[#pts + 1] = v end
	if #pts < 2 then pinch = nil return end
	local dist = (pts[1] - pts[2]).Magnitude
	local mid = (pts[1] + pts[2]) / 2
	local vx, vy = viewPoint(mid.X, mid.Y)
	if not pinch or dist < 1 then pinch = {d0 = math.max(dist, 1), z0 = zoom, ix = (vx - panX) / zoom, iy = (vy - panY) / zoom} return end
	zoom = math.clamp(pinch.z0 * dist / pinch.d0, MINZ, MAXZ)
	panX = vx - pinch.ix * zoom; panY = vy - pinch.iy * zoom
	relayout()
end
view.InputBegan:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
		if input.UserInputType == Enum.UserInputType.Touch then touches[input] = Vector2.new(input.Position.X, input.Position.Y) end
		if touchCount() >= 2 then drag = nil; pinch = nil; pinchUpdate() return end
		drag = {x = input.Position.X, y = input.Position.Y, px = panX, py = panY, input = input}
	elseif input.UserInputType == Enum.UserInputType.MouseWheel then
		local vx, vy = viewPoint(input.Position.X, input.Position.Y)
		zoomAt(input.Position.Z > 0 and 1.25 or 0.8, vx, vy)
	end
end)
UIS.InputChanged:Connect(function(input)
	if not map.Visible then return end
	if touches[input] then
		touches[input] = Vector2.new(input.Position.X, input.Position.Y)
		if touchCount() >= 2 then pinchUpdate() return end
	end
	if drag and (input.UserInputType == Enum.UserInputType.MouseMovement or input == drag.input) then
		local s = math.max(view.AbsoluteSize.X / DISP_W, 0.01)
		panX = drag.px + (input.Position.X - drag.x) / s
		panY = drag.py + (input.Position.Y - drag.y) / s
		relayout()
	end
end)
UIS.InputEnded:Connect(function(input)
	if touches[input] then touches[input] = nil; pinch = nil; drag = nil end
	if drag and (input.UserInputType == Enum.UserInputType.MouseButton1 or input == drag.input) then drag = nil end
end)
zoomIn.Activated:Connect(function() zoomAt(1.3, DISP_W / 2, DISP_H / 2) end)
zoomOut.Activated:Connect(function() zoomAt(1 / 1.3, DISP_W / 2, DISP_H / 2) end)
local function centreOnMe()
	local char = player.Character
	local root = char and char:FindFirstChild("HumanoidRootPart")
	if not root then return end
	if zoom < 1 then zoom = 1 end
	centreOn(math.clamp(root.Position.X, WX0, WX1), math.clamp(root.Position.Z, WZ0, WZ1))
end
centreMe.Activated:Connect(centreOnMe)

local function refreshMap()
	for _, a in ipairs(AREAS) do
		local card = cards[a.id]
		local open = unlocked(a)
		card.open = open
		if open then
			card.title.Text = a.name or NAME[a.id] or a.id
			if a.id == "porto" then
				card.tally.Text = "harbour coming soon"
			else
				local found = player:GetAttribute("Found_" .. a.id) or 0
				card.tally.Text = string.format("%d / %d found", found, TOTAL[a.id] or 0)
			end
		end
	end
	relayout()
end
local function refreshCount()
	local n = player:GetAttribute("SquirrelsFound") or 0
	local all = #Registry.squirrels
	countTag.Text = string.format("%d/%d", n, all)
end

-- ---------------------------------------------------------------- opening and closing ----
local function setSquirrels(open)
	if open then pg:SetAttribute("OpenPanel","collection") end
	if hudPanel then hudPanel.Visible = open end
	if open then map.Visible = false end
end
local function setMap(open)
	if open then pg:SetAttribute("OpenPanel","map") end
	map.Visible = open
	if open then refreshMap(); centreOnMe(); if hudPanel then hudPanel.Visible = false end end
end
squirrelBtn.Activated:Connect(function() setSquirrels(not squirrelOpen()) end)
mapBtn.Activated:Connect(function() setMap(not map.Visible) end)
for _, a in ipairs(AREAS) do
	if a.needs == "porto" then player:GetAttributeChangedSignal("Item_porto"):Connect(refreshMap)
	elseif a.needs then player:GetAttributeChangedSignal("Found_" .. a.needs):Connect(refreshMap) end
	player:GetAttributeChangedSignal("Found_" .. a.id):Connect(refreshMap)
end
player:GetAttributeChangedSignal("SquirrelsFound"):Connect(refreshCount)

-- the purse follows the Acorns attribute, which the server sets; a small pop so a pickup is felt as well as seen
local purseScale = Instance.new("UIScale"); purseScale.Parent = purse
local function refreshPurse()
	purseCount.Text = tostring(player:GetAttribute("Acorns") or 0)
end
player:GetAttributeChangedSignal("Acorns"):Connect(function()
	refreshPurse()
	purseScale.Scale = 1.22
	TweenService:Create(purseScale, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		{Scale = 1}):Play()
	-- a backstop: an interrupted tween once left a UIScale stuck large over the panel, and a counter frozen
	-- mid-bounce looks broken in a way that is hard to explain
	task.delay(0.6, function() if purseScale then purseScale.Scale = 1 end end)
end)
refreshPurse()
refreshCount(); refreshMap()

-- on a narrow screen (phones) the map shrinks to fit rather than covering everything
local mapScale = Instance.new("UIScale"); mapScale.Parent = map
local function fitMap()
	local vp = workspace.CurrentCamera and workspace.CurrentCamera.ViewportSize or Vector2.new(1280, 720)
	mapScale.Scale = math.clamp(math.min((vp.X - 30) / (DISP_W + 16), (vp.Y - PANEL_Y - 16) / (DISP_H + 48)), 0.45, 1)
end
if workspace.CurrentCamera then workspace.CurrentCamera:GetPropertyChangedSignal("ViewportSize"):Connect(fitMap) end
fitMap()

-- the "you are here" dot follows the player while the map is open (the chart itself stays where you dragged it)
RunService.RenderStepped:Connect(function()
	if not map.Visible then return end
	local char = player.Character
	local root = char and char:FindFirstChild("HumanoidRootPart")
	if not root then dot.Visible = false; return end
	local p = root.Position
	local cx, cz = toCanvas(math.clamp(p.X, WX0, WX1), math.clamp(p.Z, WZ0, WZ1))
	dot.Visible = true
	dot.Position = UDim2.fromOffset(cx, cz)
	local a = areaAt(p)
	here.Text = a and ("You are here: " .. (a.name or NAME[a.id] or a.id)) or "You are here"
	rs.Transparency = 0.25 + 0.35 * math.abs(math.sin(os.clock() * 2))
end)

-- the Golden Squirrel pill (DailyGui.GoldPill, computers only) sits on the panels' header line at the top right: it steps
-- aside while the map or the squirrels panel is open and comes back when they close (Shannon, Oct 1: "fix the overlap")
local pillHidden, pillWas = false, false
RunService.Heartbeat:Connect(function()
	local daily = pg:FindFirstChild("DailyGui")
	local pill = daily and daily:FindFirstChild("GoldPill")
	if not pill then return end
	if map.Visible or (hudPanel and hudPanel.Visible) then
		if pill.Visible then pillWas = true; pill.Visible = false end   -- also catches the Daily script showing it meanwhile
		pillHidden = true
	elseif pillHidden then
		pillHidden = false
		if pillWas and pill.Text ~= "" then pill.Visible = true end
		pillWas = false
	end
end)
]==]
local PAIRS = {
	{[==[	{id = "domaine", x0 = 352,  x1 = 700, z0 = -250, z1 = 30,  needs = "village"},
}]==], [==[	{id = "domaine", x0 = 352,  x1 = 700, z0 = -250, z1 = 30,  needs = "village"},
	{id = "porto",   x0 = 100,  x1 = 330, z0 = -700, z1 = -548, needs = "porto", name = "Porto Nocciola"},   -- Italy: opened by the first landing (Item_porto)
}]==]},
	{[==[local function unlocked(a) return (not a.needs) or (player:GetAttribute("Found_" .. a.needs) or 0) >= NEED end]==], [==[local function unlocked(a) if a.needs == "porto" then return (player:GetAttribute("Item_porto") or 0) >= 1 end return (not a.needs) or (player:GetAttribute("Found_" .. a.needs) or 0) >= NEED end]==]},
}
local src = s.Source
if src:find(MARK, 1, true) then print('QQ MW HudBarClient already at this version') else
	local i = src:find('local MAP_ID = ', 1, true); assert(i, 'QQ MW map start anchor missing')
	local j = src:find(END, i, true); assert(j, 'QQ MW map end anchor missing')
	src = src:sub(1, i - 1) .. BLOCK .. src:sub(j)
	for k, pr in ipairs(PAIRS) do
		local a, b = src:find(pr[1], 1, true)
		if a then src = src:sub(1, a - 1) .. pr[2] .. src:sub(b + 1) end
	end
	src = src:gsub('%-%- world%-map v%d+ %(Oct 1 2026%)\n?', '')
	s.Source = src:gsub('\n+$', '') .. '\n' .. MARK .. '\n'
	print('QQ MW HudBarClient patched: world map 126434655912945 (' .. MARK .. ')')
end
print('QQ MW DONE')
