"""patch_map_world.py MAP_ASSET_ID (Oct 1 2026): the ONE draggable world map for HudBarUI.HudBarClient.
Replaces the map panel section (from `local MAP_ID = ...` up to the Passport button code) with boundary/hudbar_map_block.lua,
adds Porto Nocciola to AREAS (opened by Item_porto), and applies the same change to the local copies:
passport/integrations/Workspace.HudBarUI.HudBarClient.lua and every copy embedded in passport/build_passport.lua.
Writes boundary/install_map_world.lua for the LIVE script (PatchModule-ready; anchors asserted). Re-runnable: a newer
block version replaces the older one (VERSION below); the same version is skipped.
Run: python patch_map_world.py 126434655912945   (from boundary/)"""
import re
import sys
from pathlib import Path

D = Path(__file__).parent
VERSION = 3
MARK = "-- world-map v%d (Oct 1 2026)" % VERSION
MARK_RE = re.compile(r"-- world-map v\d+ \(Oct 1 2026\)\n?")
asset = sys.argv[1] if len(sys.argv) > 1 else "MAPID_PLACEHOLDER"
block = (D / "hudbar_map_block.lua").read_text(encoding="utf-8").replace("MAPID_PLACEHOLDER", asset)
START_RE = re.compile(r"local MAP_ID = [0-9A-Z_]+")       # the original chart id, or an earlier world-map block
END = "-- Passport entry uses the same top-right control row"

PAIRS = [
 ('\t{id = "domaine", x0 = 352,  x1 = 700, z0 = -250, z1 = 30,  needs = "village"},\n}',
  '\t{id = "domaine", x0 = 352,  x1 = 700, z0 = -250, z1 = 30,  needs = "village"},\n'
  '\t{id = "porto",   x0 = 100,  x1 = 330, z0 = -700, z1 = -548, needs = "porto", name = "Porto Nocciola"},   -- Italy: opened by the first landing (Item_porto)\n}'),
 ('local function unlocked(a) return (not a.needs) or (player:GetAttribute("Found_" .. a.needs) or 0) >= NEED end',
  'local function unlocked(a) if a.needs == "porto" then return (player:GetAttribute("Item_porto") or 0) >= 1 end return (not a.needs) or (player:GetAttribute("Found_" .. a.needs) or 0) >= NEED end'),
]


def patch(src, label):
    if MARK in src:
        print(label, "already at v%d" % VERSION); return src
    n = 0
    pos = 0
    while True:
        m = START_RE.search(src, pos)
        if not m: break
        j = src.find(END, m.start())
        assert j > m.start(), f"{label}: end anchor missing after start {n}"
        src = src[:m.start()] + block + src[j:]
        pos = m.start() + len(block)
        n += 1
    assert n >= 1, f"{label}: map section not found"
    for old, new in PAIRS:
        if old in src: src = src.replace(old, new)
    src = MARK_RE.sub("", src)
    print(label, "patched:", n, "map section(s)")
    return src.rstrip("\n") + "\n" + MARK + "\n"


def main():
    for rel in ("../passport/integrations/Workspace.HudBarUI.HudBarClient.lua", "../passport/build_passport.lua"):
        p = D / rel
        p.write_text(patch(p.read_text(encoding="utf-8"), rel), encoding="utf-8")
    def lua_str(s):
        assert "]==]" not in s
        return "[==[" + s + "]==]"
    out = "\n".join([
        "-- install_map_world (" + MARK + "): ONE draggable world map in the LIVE workspace.HudBarUI.HudBarClient.",
        "-- Generated by boundary/patch_map_world.py from boundary/hudbar_map_block.lua - edit those, not this. Edit mode; re-runnable.",
        'local s = workspace:WaitForChild("HudBarUI"):WaitForChild("HudBarClient")',
        "local MARK = " + lua_str(MARK),
        "local END = " + lua_str(END),
        "local BLOCK = " + lua_str(block),
        "local PAIRS = {",
        *["\t{" + lua_str(o) + ", " + lua_str(n) + "}," for o, n in PAIRS],
        "}",
        "local src = s.Source",
        "if src:find(MARK, 1, true) then print('QQ MW HudBarClient already at this version') else",
        "\tlocal i = src:find('local MAP_ID = ', 1, true); assert(i, 'QQ MW map start anchor missing')",
        "\tlocal j = src:find(END, i, true); assert(j, 'QQ MW map end anchor missing')",
        "\tsrc = src:sub(1, i - 1) .. BLOCK .. src:sub(j)",
        "\tfor k, pr in ipairs(PAIRS) do",
        "\t\tlocal a, b = src:find(pr[1], 1, true)",
        "\t\tif a then src = src:sub(1, a - 1) .. pr[2] .. src:sub(b + 1) end",
        "\tend",
        "\tsrc = src:gsub('%-%- world%-map v%d+ %(Oct 1 2026%)\\n?', '')",
        "\ts.Source = src:gsub('\\n+$', '') .. '\\n' .. MARK .. '\\n'",
        "\tprint('QQ MW HudBarClient patched: world map " + asset + " (' .. MARK .. ')')",
        "end",
        "print('QQ MW DONE')",
        ""])
    (D / "install_map_world.lua").write_text(out, encoding="utf-8")
    print("wrote install_map_world.lua for asset", asset, "version", VERSION)


if __name__ == "__main__":
    main()
