-- tidepools_place (Oct 4 2026, Shannon's go on the Blender preview https://claude.ai/artifact/Ho8ATTm27MMHdvcfRqXFqT):
-- puts the imported TidePoolShelf + TidePoolWater meshes (roblox-props/italy/tidepools, gen_tidepools.py) at their exact
-- centres, moves Codex's ring basins to ServerStorage.TidePoolBackup.OldRingPools (not deleted), and adds the sea life
-- (positions + heights computed offline from the same heightfield). Generated by make_place_lua.py - edit that, not this.
-- No asserts after the first edit: warn + return.
local SHELF,WATER={298.2500,-54.3327,-784.5000,31.5000,6.3345,52.0000},{297.5257,-51.8245,-785.7985,17.6870,0.4850,35.2698}
local LIFE={{"starfish",291.00,-52.720,-783.40,10},{"starfish",294.40,-52.720,-794.60,40},{"starfish",303.20,-52.720,-801.00,75},{"anemone",295.60,-52.635,-771.60,0},{"anemone",296.40,-52.096,-786.90,0},{"anemone",290.30,-52.720,-780.20,0},{"seaweed",292.20,-51.629,-768.40,0},{"seaweed",297.70,-51.423,-773.90,0},{"seaweed",289.20,-51.892,-781.80,0},{"seaweed",292.90,-51.520,-786.90,0},{"seaweed",291.00,-51.807,-792.30,0},{"seaweed",297.40,-51.837,-797.20,0},{"seaweed",300.70,-51.790,-799.00,0},{"seaweed",306.20,-51.688,-803.50,0},{"seaweed",299.30,-52.975,-776.00,0},{"shell",293.40,-51.989,-771.90,0},{"shell",297.30,-51.979,-785.60,0},{"shell",294.90,-52.720,-796.90,0},{"shell",304.40,-52.720,-801.60,0},{"shell",298.30,-52.010,-777.80,0},{"crab",299.40,-51.292,-790.40,-60}}
local src=workspace:FindFirstChild('tidepools_roblox')
if not src then warn('QP@ABORT import not found') return end
local shelf,water=src:FindFirstChild('TidePoolShelf',true),src:FindFirstChild('TidePoolWater',true)
if not (shelf and water) then warn('QP@ABORT pieces missing') return end
for _,e in ipairs({{shelf,SHELF},{water,WATER}}) do
	local p,t=e[1],e[2]
	if (p.Size-Vector3.new(t[4],t[5],t[6])).Magnitude>0.2 then warn('QP@ABORT size',p.Name,p.Size,t[4],t[5],t[6]) return end
end
local cove=workspace.PortoNocciola['14 Lighthouse coast']:FindFirstChild('Cala della Sabbia and tide pools')
if not cove then warn('QP@ABORT no cove') return end
if cove:FindFirstChild('Natural tide pools') then warn('QP@ABORT already placed') return end
local SS=game:GetService('ServerStorage')
-- ---- edits from here ----
local bk=SS:FindFirstChild('TidePoolBackup') or Instance.new('Folder') bk.Name='TidePoolBackup' bk.Parent=SS
local old=bk:FindFirstChild('OldRingPools') or Instance.new('Folder') old.Name='OldRingPools' old.Parent=bk
local moved=0
for _,d in ipairs(cove:GetChildren()) do
	if d:IsA('BasePart') and (d.Name=='Tide pool rock rim' or d.Name=='Tide pool rock basin' or d.Name=='Still tide pool water' or d.Name=='Tide pool shells') then d.Parent=old moved+=1 end
end
local F=Instance.new('Folder') F.Name='Natural tide pools' F.Parent=cove
F:SetAttribute('Built','Oct 4 2026 - mesh shelf + pools replacing the ring basins (backup: ServerStorage.TidePoolBackup.OldRingPools)')
F:SetAttribute('Source','roblox-props/italy/tidepools (gen_tidepools.py, make_place_lua.py)')
shelf.Anchored=true shelf.CanCollide=true shelf.CanTouch=false shelf.CanQuery=true shelf.CastShadow=true
pcall(function() shelf.CollisionFidelity=Enum.CollisionFidelity.PreciseConvexDecomposition end)
shelf.Material=Enum.Material.Plastic
shelf.CFrame=CFrame.new(SHELF[1],SHELF[2],SHELF[3]) shelf.Parent=F
water.Anchored=true water.CanCollide=false water.CanTouch=false water.CanQuery=false water.CastShadow=false
water.Material=Enum.Material.SmoothPlastic water.Color=Color3.fromRGB(96,182,188) water.Transparency=0.38 water.Reflectance=0.12
water.CFrame=CFrame.new(WATER[1],WATER[2],WATER[3]) water.Parent=F
if #src:GetChildren()==0 then src:Destroy() end
-- ---- sea life ----
local L=Instance.new('Folder') L.Name='Sea life' L.Parent=F
local rng=Random.new(1004)
local function part(name,size,cf,color,shape)
	local p=Instance.new('Part') p.Name=name p.Size=size p.CFrame=cf p.Color=color p.Material=Enum.Material.SmoothPlastic
	if shape then p.Shape=shape end
	p.Anchored=true p.CanCollide=false p.CanTouch=false p.CanQuery=false p.CastShadow=false p.Parent=L return p
end
local made=0
for _,e in ipairs(LIFE) do
	local k,pos,ex=e[1],Vector3.new(e[2],e[3],e[4]),e[5]
	if k=='starfish' then
		local col=({Color3.fromRGB(232,122,52),Color3.fromRGB(196,72,96),Color3.fromRGB(240,150,60)})[made%3+1]
		local base=CFrame.new(pos+Vector3.new(0,0.05,0))*CFrame.Angles(0,math.rad(ex),0)
		part('Starfish centre',Vector3.new(0.12,0.34,0.34),base*CFrame.Angles(0,0,math.rad(90)),col,Enum.PartType.Cylinder)
		for i=0,4 do part('Starfish arm',Vector3.new(0.2,0.09,0.55),base*CFrame.Angles(0,math.rad(72*i),0)*CFrame.new(0,0,-0.36),col) end
	elseif k=='anemone' then
		local col=({Color3.fromRGB(226,98,128),Color3.fromRGB(110,170,120),Color3.fromRGB(232,120,150)})[made%3+1]
		part('Sea anemone',Vector3.new(0.4,0.42,0.42),CFrame.new(pos+Vector3.new(0,0.2,0))*CFrame.Angles(0,0,math.rad(90)),col,Enum.PartType.Cylinder)
		for i=0,6 do part('Sea anemone tentacle',Vector3.new(0.13,0.13,0.13),CFrame.new(pos+Vector3.new(0,0.42,0))*CFrame.Angles(0,math.rad(51*i),0)*CFrame.new(0,0.03,-0.17),col:Lerp(Color3.new(1,1,1),0.25),Enum.PartType.Ball) end
	elseif k=='seaweed' then
		for i=0,2 do
			local h=rng:NextNumber(0.6,1.0)
			part('Seaweed frond',Vector3.new(0.1,h,0.3),CFrame.new(pos)*CFrame.Angles(0,math.rad(rng:NextNumber(0,360)),0)*CFrame.Angles(math.rad(rng:NextNumber(-22,22)),0,0)*CFrame.new(0,h/2-0.05,0),Color3.fromRGB(58,112,52):Lerp(Color3.fromRGB(96,128,44),rng:NextNumber()))
		end
	elseif k=='shell' then
		part('Snail shell',Vector3.new(0.3,0.22,0.3),CFrame.new(pos+Vector3.new(0,0.08,0))*CFrame.Angles(0,math.rad(rng:NextNumber(0,360)),math.rad(15)),Color3.fromRGB(122,104,86),Enum.PartType.Ball)
	elseif k=='crab' then
		local c=CFrame.new(pos+Vector3.new(0,0.17,0))*CFrame.Angles(0,math.rad(ex),0) local red=Color3.fromRGB(214,92,52)
		part('Crab body',Vector3.new(0.8,0.3,0.6),c,red,Enum.PartType.Ball)
		for s=-1,1,2 do
			part('Crab claw',Vector3.new(0.26,0.2,0.3),c*CFrame.new(s*0.42,0.05,-0.42),red,Enum.PartType.Ball)
			part('Crab eye',Vector3.new(0.08,0.08,0.08),c*CFrame.new(s*0.12,0.2,-0.26),Color3.fromRGB(25,25,25),Enum.PartType.Ball)
			for j=0,2 do part('Crab leg',Vector3.new(0.34,0.06,0.06),c*CFrame.new(s*0.48,-0.08,-0.1+j*0.17)*CFrame.Angles(0,0,math.rad(-s*25)),red) end
		end
	end
	made+=1
end
game:GetService('ChangeHistoryService'):SetWaypoint('Natural tide pools (mesh)')
warn('QP@PLACED ring parts moved',moved,'life items',made,'parts',#L:GetChildren())
local cam=workspace.CurrentCamera
local t=Vector3.new(295,-52,-786)
cam.Focus=CFrame.new(t)
cam.CFrame=CFrame.lookAt(Vector3.new(279,-38,-768),t)
