-- tidepools_swap (Oct 4 2026, round 3: pool lips so the water never runs out over lower rock; Shannon flagged a spill):
-- replace the placed TidePoolShelf/TidePoolWater with the re-imported ones (spare model 'tidepools_roblox'), at the new
-- centres from tidepools_data.json. The old pieces go to ServerStorage.TidePoolBackup.Round2. Generated by make_swap_lua.py.
local SHELF,WATER={298.2500,-54.3327,-784.5000,31.5000,6.3345,52.0000},{297.7702,-51.8245,-785.7891,17.1070,0.4850,35.1203}
local F=workspace.PortoNocciola['14 Lighthouse coast']['Cala della Sabbia and tide pools']:FindFirstChild('Natural tide pools')
local src=workspace:FindFirstChild('tidepools_roblox')
if not (F and src) then warn('QS3@ABORT missing',F,src) return end
local ns,nw=src:FindFirstChild('TidePoolShelf',true),src:FindFirstChild('TidePoolWater',true)
local os_,ow=F:FindFirstChild('TidePoolShelf'),F:FindFirstChild('TidePoolWater')
if not (ns and nw and os_ and ow) then warn('QS3@ABORT pieces',ns,nw,os_,ow) return end
for _,e in ipairs({{ns,SHELF},{nw,WATER}}) do
	if (e[1].Size-Vector3.new(e[2][4],e[2][5],e[2][6])).Magnitude>0.2 then warn('QS3@ABORT size',e[1].Name,e[1].Size) return end
end
local bk=game:GetService('ServerStorage'):FindFirstChild('TidePoolBackup')
if not bk then warn('QS3@ABORT no backup folder') return end
-- ---- edits ----
local r2=Instance.new('Folder') r2.Name='Round2' r2.Parent=bk
os_.Parent=r2 ow.Parent=r2
ns.Anchored=true ns.CanCollide=true ns.CanTouch=false ns.CanQuery=true ns.CastShadow=true
pcall(function() ns.CollisionFidelity=Enum.CollisionFidelity.PreciseConvexDecomposition end)
ns.Material=Enum.Material.Plastic
ns.CFrame=CFrame.new(SHELF[1],SHELF[2],SHELF[3]) ns.Parent=F
nw.Anchored=true nw.CanCollide=false nw.CanTouch=false nw.CanQuery=false nw.CastShadow=false
nw.Material=ow.Material nw.Color=ow.Color nw.Transparency=ow.Transparency nw.Reflectance=ow.Reflectance
nw.CFrame=CFrame.new(WATER[1],WATER[2],WATER[3]) nw.Parent=F
if #src:GetChildren()==0 then src:Destroy() end
game:GetService('ChangeHistoryService'):SetWaypoint('Tide pools: rims round the pools')
warn('QS3@OK shelf',ns.Size,'water',nw.Size)
