-- ChatterLines (ModuleScript in workspace.SquirrelChatter): what the squirrels of Porto Nocciola, and the two church mice,
-- say to a passer-by (Shannon, Oct 11 2026: "squirrels in the Italy map randomly talk more to passers by"; "church mice at
-- both churches tell players that Jesus loves them as they walk by, with an Italian and French flair"). One pool per
-- registry id; the client picks a line at random, never the same one twice running. Keep a line under about 90 letters
-- so the bubble stays small. always = true: this one speaks whether or not you have found it (the mice).
return {
	-- ---------- the church mice ----------
	church_mouse_cousin = {always = true, lines = {
		"Buongiorno, amico! Jesus loves you - and so does this little mouse.",
		"Psst... Gesu ti ama. Jesus loves you. Pass it on!",
		"Ciao! The bells say it every hour: Jesus loves you.",
		"Welcome to Santa Marina. Jesus loves you - never forget it, okay?",
		"Mamma mia, what a beautiful day! Jesus loves you, you know.",
		"I may be small, but this is big news: Jesus loves you!",
		"Dio ti benedica. God bless you, friend - Jesus loves you.",
		"Quiet as a church mouse... except about this: Jesus loves you!",
	}},
	church_mouse = {always = true, lines = {
		"Bonjour, mon ami! Jesus loves you - and that is the best news in all of France.",
		"Psst... Jesus t'aime. Jesus loves you. Pass it on!",
		"Bienvenue! The bells say it every hour: Jesus loves you.",
		"Ooh la la, what a lovely day! Jesus loves you, you know.",
		"I may be small, but this is big news: Jesus loves you!",
		"Que Dieu te benisse. God bless you, friend - Jesus loves you.",
		"Quiet as a church mouse... except about this: Jesus loves you!",
		"Merci for stopping by! Remember: Jesus loves you.",
	}},

	-- ---------- the harbour ----------
	customs_squirrel = {lines = {
		"Anything to declare? No? Then welcome to Porto Nocciola!",
		"Passport, please... ah, you again. Avanti, avanti!",
		"You are dripping on my floor. Did you come by waterfall again?",
		"A stamp for you, a stamp for me. Everyone loves a stamp.",
	}},
	fishmonger_squirrel = {lines = {
		"Pesce fresco! Fresh fish! Fresher than the seagulls deserve.",
		"Got crabs? Bring them to Beppe, I pay in acorns! The golden ones pay best.",
		"Enzo catches the crabs, I sell the crabs. The crabs have not agreed to any of this.",
		"A crab trap and a little patience, and you are in business. The crab is not.",
		"Those seagulls owe me three sardines and an apology.",
		"The octopus is not for sale. He is a colleague.",
	}},
	deckhand_squirrel = {lines = {
		"Hop in, hop in! Mind the puddle. Mind the other puddle.",
		"The Stella Marina has never sunk. Well, not all the way.",
		"I swab the deck, I coil the rope, I nap. Mostly the nap.",
		"A sailor's life for me! Right after lunch.",
	}},
	netmender_squirrel = {lines = {
		"Every net has a hole. The trick is knowing which ones are on purpose.",
		"Sit, sit. Nonno Reti has a story. It is a long one.",
		"I mended this net in 1978. Or was it the other net?",
		"The sea gives, the sea takes, and the sea tangles everything.",
	}},
	gelato_squirrel = {lines = {
		"Today's flavour is Lemon Surprise. The surprise is how sour it is.",
		"One scoop or two? Three is also a number.",
		"Gelato tastes better by the sea. This is science.",
		"Tomorrow's flavour is named after whoever walks in first. Be nice.",
	}},
	boatpainter_squirrel = {lines = {
		"Fresh paint! Fresh paint! Why is everyone touching the fresh paint?",
		"This blue took me three tries. The sea got it right first time.",
		"My overalls have had more coats than the Nuova Alba.",
		"A boat without a name is just a floating bathtub.",
	}},
	realtor_squirrel = {lines = {
		"Sea view, sea breeze, sea gulls. Three for the price of one!",
		"Cosy, charming, compact. That means small. Very small.",
		"From the roof you can see the sea. Do not stand on the roof.",
		"Location, location, and a little bit more location.",
	}},
	italytourist_squirrel = {lines = {
		"Ciao! That means hello. Also goodbye. Also 'where is the bathroom?'",
		"Y'all, this is prettier than the pecan-pie contest, and that's saying something.",
		"Say cheese! Oh, wait, how do you say cheese in Italian? Ciao?",
		"I have taken four hundred pictures of the same boat. It keeps moving.",
	}},
	tightrope_squirrel = {lines = {
		"Do not look down. I say that to myself, mostly.",
		"Signora Rosa says get off her washing line. Almost there!",
		"A little wobble is part of the act. The big wobble is not.",
		"Balance is easy. It is the falling that takes practice.",
	}},
	seacaptain_squirrel = {lines = {
		"I steer by the stars. On cloudy nights, by the bakery.",
		"The sea is calm today. Suspiciously calm.",
		"All aboard the Azzurra! Life jackets are under the... somewhere.",
		"A captain never gets lost. He takes the scenic route.",
	}},
	sunbather_squirrel = {lines = {
		"Any minute now, the perfect wave. Any minute.",
		"The sun is free, the view is free, the towel was five acorns.",
		"Surf's up! Well, surf's... level. Surf's here.",
		"Shh. I am working on my tan. It is very serious work.",
	}},
	crabcatcher_squirrel = {lines = {
		"Walk sideways. Think sideways. Be the crab.",
		"The crabs know it is me. The tourists do not.",
		"Want to catch crabs? Get a trap in the Acorn Store!",
		"One pinch and you learn. Two pinches and you learn properly.",
	}},
	-- (Tonio the Conductor is not here: TonioTalk already speaks for him when you walk up)
	lifeguard_squirrel = {lines = {
		"No swimming right after pizza! Wait half an hour. Twenty minutes for a small slice.",
		"I have whistled at every wave this summer. Not one has listened.",
		"No running! No splashing! No... fine, a little splashing.",
		"Pizza, then a nap, then a swim. In that order. The order matters.",
		"The water is lovely. I checked it from up here.",
		"Safety first! Sunscreen second. Gelato third. Pizza much, much later.",
	}},
	octopus_squirrel = {lines = {
		"The octopus took my bait. Then my bucket. Then my hat.",
		"Eight arms against two. The maths were never on my side.",
		"Today is the day I catch him. I say that every day.",
		"Have you seen a bucket? Red, with a dent? He has it.",
	}},

	-- ---------- the Via della Piazza ----------
	sassyshopper_squirrel = {lines = {
		"I am not shopping. I am investing in handbags.",
		"Excuse me, do you have this in a smaller size and a bigger discount?",
		"Three bags, two paws, one problem.",
		"Darling, that colour is so last summer. Mine is this summer.",
	}},
	pogo_squirrel = {lines = {
		"Boing! Boing! Boing! Sorry, I cannot stop. Literally.",
		"Up, down, up, down. The view changes a lot.",
		"I have bounced over this whole piazza. Twice. Today.",
		"Pogo tip: never stop. Second tip: there is no second tip.",
	}},
	pizzadelivery_squirrel = {lines = {
		"Thirty minutes or it is free. It is usually free.",
		"Hot pizza coming through! Well, warm pizza. Pizza.",
		"The address says third floor. There are two floors.",
		"I deliver pizza by day. By night I deliver more pizza.",
	}},
	baker_squirrel = {lines = {
		"Bread is out at six, gone by seven, missed by eight.",
		"The secret ingredient is love. And a lot of flour.",
		"Smell that? That is tomorrow's breakfast.",
		"A warm loaf can fix almost anything. Almost.",
	}},
	giulia_market_squirrel = {lines = {
		"Tomatoes, tomatoes! Red as a sunburnt tourist!",
		"Squeeze the peach, not the seller.",
		"Fresh today, fresher yesterday, who's counting?",
		"Buy two, I throw in a smile. Buy three, two smiles.",
	}},
	officer_acorn_police_squirrel = {lines = {
		"Move along, nothing to see here. Except the view. Look at the view.",
		"Acorn Police! Have you seen any suspicious nuts?",
		"Jaywalking is a crime. Jay-bouncing, I am still looking up.",
		"I keep the peace. The pizza keeps me.",
	}},
	goldenyears_squirrel = {lines = {
		"Sixty years together. He still holds my paw crossing the piazza. Even when there are no carts.",
		"The secret? Say sorry first, laugh second, and share the last cannoli.",
		"We met right here, on this bench. It was a different bench. Same us.",
		"She still laughs at my jokes. I still tell the same ones. It works.",
		"We danced at every festa since 1966. Slower now, but still every one.",
		"Grow old with someone who makes you laugh. Then keep laughing. That is all.",
		"He forgets the bread. I forget to be cross. Sixty years of that.",
		"Come, sit a moment. The bench has room, and so do our hearts.",
	}},
	goodneighbor_squirrel = {lines = {
		"Need sugar? Need a ladder? Need a chat? I have all three.",
		"Your laundry is dry, your plants are watered, and I fed your cat.",
		"A good neighbour knocks. A great neighbour brings cake.",
		"If you need anything, I am right here. Always right here.",
	}},
	operasinger_squirrel = {lines = {
		"Laaaa! Pardon me, the high note just comes out sometimes.",
		"Every aria needs an audience. You will do nicely.",
		"I sing for the piazza. The piazza has not asked me to stop. Yet.",
		"Bravo! Brava! Bravissimo! That is for me, not you. Sorry.",
	}},
	broomseller_squirrel = {lines = {
		"A broom! A broom! Your doorstep has never looked worse!",
		"Free demonstration with every broom. Also without.",
		"This one sweeps. This one really sweeps. This one is a mop.",
		"Clean steps, clean heart. Buy a broom.",
	}},
	accordion_squirrel = {lines = {
		"Thirty years I play for the Fat Lady. Thirty years she sings over me.",
		"Request? I know every song. I play all of them the same.",
		"The accordion is heavy. The tips are light. Such is music.",
		"Dance if you like! Nobody is watching. Everybody is watching.",
	}},
	pizzamaker_squirrel = {lines = {
		"Watch this spin! Watch it! Watch out!",
		"Thin crust, thick crust, I make them all. Some on purpose.",
		"The oven is hot, the dough is ready, and the ceiling is a little bit pizza.",
		"Pineapple? In Porto Nocciola? We do not speak of this.",
	}},
	clockmaker_squirrel = {lines = {
		"The clock is right twice a day. I am working on a third.",
		"Tick, tock, tick... tock... there it goes again.",
		"Time flies. My clocks, sadly, do not.",
		"Do you have the time? Neither does the tower, apparently.",
	}},
	postcard_squirrel = {lines = {
		"Wish you were here! You are here. Buy a postcard anyway.",
		"A postcard a day keeps the family away. Happily, I mean.",
		"This one has the sea, this one has the sea, this one has the sea at night.",
		"Stamps are extra. Smiles are included.",
	}},

	-- ---------- the Groves ----------
	lemonseller_squirrel = {lines = {
		"Lemons! Fresh from the tree behind me. Do not look at the tree behind me.",
		"Sour face? Try a lemon. Still sour? Try two.",
		"When life gives you lemons, sell them. That is business.",
		"These lemons saw the sunrise this morning. So did I. We are both tired.",
	}},
	olivepicker_squirrel = {lines = {
		"One for the basket, one for me. The basket is patient.",
		"Olive picking is slow work. Olive eating is fast work.",
		"These trees are older than the town. They have seen things.",
		"An olive a day keeps the... hmm. Keeps something away.",
	}},
	snorkel_squirrel = {lines = {
		"Gerald says hello. The fish. All of the fish are Gerald.",
		"Blub blub blub. Oh, sorry, I still had the snorkel in.",
		"The bay is full of wonders. Also a flip-flop. Just the one.",
		"Today I saw a fish so big it had its own smaller fish.",
	}},
	hiker_squirrel = {lines = {
		"The watchtower is four minutes away. I packed for three days.",
		"Always carry water, a map, and a snack. Mostly the snack.",
		"Which way is up? Trick question. Up is always up.",
		"I have hiked this path a hundred times. It is still uphill.",
	}},
	cliffdiver_squirrel = {lines = {
		"Ten out of ten! The judges agree. I am the judges.",
		"The trick is to jump before you think. Thinking is for the climb up.",
		"Splash first, questions later.",
		"From up here the sea looks small. From the sea, I look small. Fair.",
	}},
	stargazer_squirrel = {lines = {
		"I found three new stars last night. Two were the lighthouse.",
		"The stars are out all day too. The sun just talks over them.",
		"Make a wish! No, the other one, that one is a plane.",
		"Look up. No, further up. There. That is the one I named after you.",
	}},
	treasurehunter_squirrel = {lines = {
		"The treasure is where the gulls will not land. Think about it. I have, for years.",
		"Forty-two bottle caps, a spoon, and someone's car keys. Getting warmer. I can feel it.",
		"Three paces from the crooked rock, when the shadow points at the sea. Or was it the moon?",
		"X marks the spot. Sadly, so do all the other X's.",
		"Real treasure does not shine, you know. It waits. So do I. Mostly it waits.",
		"The map was drawn by a seagull. It is mostly circles. Seagulls love circles.",
		"Shh. Do you hear that? The sand is keeping a secret. Sand is terrible at secrets.",
		"They say a pirate buried his heart on this beach. I am looking for his lunchbox.",
	}},
	lighthousekeeper_squirrel = {lines = {
		"Forty years I keep the light. The light has never once thanked me.",
		"Fog tonight. Or steam from the pasta. Hard to say.",
		"I carry a lantern in case the lighthouse forgets.",
		"Ships see my light from ten miles away. My wife sees my socks from two.",
	}},
	keeperswife_squirrel = {lines = {
		"Married him for the view. Stayed for the laundry. So much laundry.",
		"Up those stairs twice a day with a basket. My knees have opinions.",
		"The sea is lovely, dear. Now bring in the washing before it is sea too.",
		"Forty years of lighthouse. Forty years of damp socks.",
	}},
	photographer_squirrel = {lines = {
		"One more! Just one more! Okay, one more after that.",
		"Say 'formaggio'! That is cheese. Hold it... hold it...",
		"The light is perfect right now. And now. And... missed it.",
		"I have a thousand sunset pictures. This one will be different.",
	}},
	droneflyer_squirrel = {lines = {
		"The drone has been up the lighthouse more than the keeper has.",
		"Smile! You are on camera. Very small camera. Very high up.",
		"Battery at five percent. Which means a crash landing. Which means a landing.",
		"From up there the whole town looks like a postcard. A wobbly one.",
	}},
	seaglass_squirrel = {lines = {
		"Green, brown, white, blue. Still looking for the purple one.",
		"The sea makes the glass smooth. Patience makes the collector.",
		"Every piece was a bottle once. Every bottle was a story.",
		"Look down when you walk the beach. The best things are small.",
	}},
	guitarist_squirrel = {lines = {
		"I know one song. Would you like to hear it again?",
		"Strum, strum, strum. That is the whole song, actually.",
		"Music is the language of the heart. Mine only knows one sentence.",
		"Requests welcome, as long as you request this song.",
	}},
	butterfly_squirrel = {lines = {
		"Three hats and a sandwich. Not one butterfly. The net is cursed.",
		"Shh! There is one! There it... goes. There it goes.",
		"Butterflies are faster than they look. Hats are slower.",
		"One day I will catch one. Today I caught a leaf. Progress.",
	}},
}
