-- codex_passport_v2_rules (EDIT ONLY)
local F=workspace.Passport
local catalogue=assert(loadstring(F.Catalogue.Source))()
local journalSource=F.Journal.Source:gsub("require%(script.Parent.Catalogue%)","(...)",1)
local J=assert(loadstring(journalSource))(catalogue)
assert(#catalogue==22)
local seen={};for _,e in ipairs(catalogue)do assert(not seen[e.id]);seen[e.id]=true end
assert(J.clean("fake",{at=2,data={}})==nil)
assert(J.clean("race",{at=0/0,data={}})==nil)
local m=J.merge({book={at=10,data={title="Old"}}},{book={at=20,data={title="New"}},hoop={at=2,data={streak=3,prize=9}}})
assert(m.book.data.title=="New" and m.hoop.data.prize==9)
assert(J.merge(m,{book={at=5,data={title="Stale"}}}).book.data.title=="New")
local eligible=function(e)return e.area=="forest" end
local batch=J.nextBatch(nil,eligible,{})
assert(#J.ids(batch.ids)==5 and not J.batchDone(batch))
batch.done=batch.ids;assert(J.batchDone(batch))
local nextBatch=J.nextBatch(batch,eligible,{})
assert(#J.ids(nextBatch.ids)==0 and nextBatch.done=="","completed pages never recycle into Outings")
local unlocked=J.nextBatch(nextBatch,function(e)return not e.bonus end,{})
assert(#J.ids(unlocked.ids)==5 and not table.find(J.ids(unlocked.ids),"find"),"new areas offer new activities")
local memories={find={at=2,data={name="Test"}}}
local fresh=J.nextBatch(nil,function(e)return not e.bonus end,memories)
assert(not table.find(J.ids(fresh.ids),"find") and #J.ids(fresh.ids)==5)
assert(not table.find(J.ids(fresh.ids),"keeper"))
local function say(id,d)return J.describe(id,{at=10,data=d},"SelBell")end
assert(say("rescue",{}):find("SelBell saves the day!",1,true))
assert(say("hoop",{baskets=0}):find("practice makes perfect",1,true))
assert(say("hoop",{baskets=3,streak=3,prize=9}):find("Won 9 acorns",1,true))
assert(say("race",{cs=6200,previousBest=6500,improvement=300,rank=2,scope="global",boardReady=true}):find("0:03.00 faster",1,true))
assert(say("race",{cs=6200,previousBest=6200,improvement=0,rank=1,scope="server"}):find("in this server",1,true))
assert(say("race",{cs=6200,scope="unavailable",boardReady=true}):find("unavailable",1,true))
assert(say("coffee",{boost=35,seconds=300}):find("35%%"))
assert(say("gold",{name="Picnic Pierre",area="Rue de Noisette",prize=30}):find("30 acorns",1,true))
assert(say("glace",{flavours="Lavande, Fraise"}):find("Lavande, Fraise",1,true))
assert(say("hat",{hat="blue beret"}):find("blue beret",1,true))
assert(say("baguette",{seconds=83,prize=8}):find("1 min 23 sec",1,true))
local encoded=game:GetService("HttpService"):JSONEncode(m)
assert(J.merge(game:GetService("HttpService"):JSONDecode(encoded),{}).book.data.title=="New")
local Rules=assert(loadstring(F.Rules.Source))()
local state={stamps={},last=0,outings=0}
Rules.record(state,"find",21000,seen);Rules.record(state,"rescue",21000,seen);Rules.record(state,"book",21000,seen)
assert(state.outings==1 and not Rules.record(state,"book",21000,seen))
warn("QQ P2 RULES PASS: 22 ids; saved memory merge/roundtrip; batches of 5; no repeated completed outings; details; daily compatibility")
